# Database connection settings
hibernate.connection.url=jdbc:mysql://localhost:3306/master?useSSL=false&serverTimezone=UTC
hibernate.connection.username=root
hibernate.connection.password=audience1wise1dioxide1tucking1fifty1boil1sublime

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=create
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.connection.pool_size=10