# Database connection settings
hibernate.connection.url=jdbc:mysql://127.0.0.1:3306/master
hibernate.connection.username=root
hibernate.connection.password=PUT_PASSWORD_HERE

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=create